spring.application.name=ka66-mail-service

#mail
spring.mail.host=xx
spring.mail.port=xx
spring.mail.username=xx
spring.mail.password=xx
spring.mail.properties.mail.smtp.auth=xx
spring.mail.properties.mail.smtp.starttls.enable=xx

#Swagger UI
springdoc.api-docs.enabled=xx
springdoc.swagger-ui.enabled=xx